ALTER TABLE landing_pages
  ADD COLUMN form_section_label VARCHAR(120) NULL AFTER intro_text,
  ADD COLUMN form_section_title VARCHAR(255) NULL AFTER form_section_label,
  ADD COLUMN form_section_intro TEXT NULL AFTER form_section_title,
  ADD COLUMN check_aside_title VARCHAR(160) NULL AFTER form_section_intro,
  ADD COLUMN check_aside_text TEXT NULL AFTER check_aside_title,
  ADD COLUMN process_label VARCHAR(120) NULL AFTER check_aside_text,
  ADD COLUMN process_title VARCHAR(255) NULL AFTER process_label,
  ADD COLUMN process_intro TEXT NULL AFTER process_title,
  ADD COLUMN process_step_1_title VARCHAR(180) NULL AFTER process_intro,
  ADD COLUMN process_step_1_text TEXT NULL AFTER process_step_1_title,
  ADD COLUMN process_step_2_title VARCHAR(180) NULL AFTER process_step_1_text,
  ADD COLUMN process_step_2_text TEXT NULL AFTER process_step_2_title,
  ADD COLUMN process_step_3_title VARCHAR(180) NULL AFTER process_step_2_text,
  ADD COLUMN process_step_3_text TEXT NULL AFTER process_step_3_title,
  ADD COLUMN conversion_label VARCHAR(120) NULL AFTER process_step_3_text,
  ADD COLUMN conversion_title VARCHAR(255) NULL AFTER conversion_label,
  ADD COLUMN conversion_text TEXT NULL AFTER conversion_title,
  ADD COLUMN trust_label VARCHAR(120) NULL AFTER conversion_text,
  ADD COLUMN trust_title VARCHAR(255) NULL AFTER trust_label,
  ADD COLUMN trust_intro TEXT NULL AFTER trust_title,
  ADD COLUMN problems_label VARCHAR(120) NULL AFTER trust_intro,
  ADD COLUMN problems_title VARCHAR(255) NULL AFTER problems_label,
  ADD COLUMN reviews_label VARCHAR(120) NULL AFTER problems_title,
  ADD COLUMN reviews_title VARCHAR(255) NULL AFTER reviews_label,
  ADD COLUMN reviews_intro TEXT NULL AFTER reviews_title,
  ADD COLUMN hero_badges_json TEXT NULL AFTER reviews_intro,
  ADD COLUMN trust_cards_json TEXT NULL AFTER hero_badges_json,
  ADD COLUMN problem_cards_json TEXT NULL AFTER trust_cards_json;

CREATE TABLE landing_page_reviews (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  landing_page_id INT NOT NULL,
  author_name VARCHAR(160) NOT NULL,
  author_location VARCHAR(160) NULL,
  rating TINYINT UNSIGNED NOT NULL DEFAULT 5,
  quote_text TEXT NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_landing_page_reviews_page (landing_page_id),
  INDEX idx_landing_page_reviews_active (is_active, sort_order)
);
