<?php
declare(strict_types=1);

// Let op: 'key', 'value' en 'label' worden server-side gevalideerd in
// actions/create_lead.php — wijzig die niet zonder de backend mee te nemen.
// 'layout', 'lucide', 'num' en 'desc' zijn puur presentatie (ketelcheck-wizard).

return [
    [
        'step' => 1,
        'key' => 'probleem',
        'label' => 'Wat is het probleem?',
        'help_text' => 'Kies wat het meest lijkt op uw situatie.',
        'type' => 'options',
        'layout' => 'tile',
        'required' => true,
        'options' => [
            [
                'value' => 'storing',
                'label' => 'Storing',
                'icon' => '⚠',
                'lucide' => 'triangle-alert',
            ],
            [
                'value' => 'geen_warm_water',
                'label' => 'Geen warm water',
                'icon' => '♨',
                'lucide' => 'flame',
            ],
            [
                'value' => 'lekkage',
                'label' => 'Lekkage',
                'icon' => '💧',
                'lucide' => 'droplet',
            ],
            [
                'value' => 'drukverlies',
                'label' => 'Drukverlies',
                'icon' => '↘',
                'lucide' => 'trending-down',
            ],
            [
                'value' => 'ketel_valt_uit',
                'label' => 'Ketel valt uit',
                'icon' => '⏻',
                'lucide' => 'power',
            ],
            [
                'value' => 'maakt_lawaai',
                'label' => 'Maakt lawaai',
                'icon' => '🔊',
                'lucide' => 'volume-2',
            ],
            [
                'value' => 'oude_ketel',
                'label' => 'Oude ketel',
                'icon' => '⌛',
                'lucide' => 'hourglass',
            ],
            [
                'value' => 'anders',
                'label' => 'Anders',
                'icon' => '?',
                'lucide' => 'circle-help',
            ],
        ],
    ],

    [
        'step' => 2,
        'key' => 'gewenste_hulp',
        'label' => 'Wat wilt u laten doen?',
        'help_text' => 'Zo kan de monteur beter inschatten wat nodig is.',
        'type' => 'options',
        'layout' => 'tile',
        'required' => true,
        'options' => [
            [
                'value' => 'reparatie',
                'label' => 'Reparatie',
                'icon' => '🔧',
                'lucide' => 'wrench',
            ],
            [
                'value' => 'vervanging',
                'label' => 'Vervangen',
                'icon' => '✓',
                'lucide' => 'replace',
            ],
            [
                'value' => 'onderhoud',
                'label' => 'Onderhoud',
                'icon' => '⚙',
                'lucide' => 'settings',
            ],
            [
                'value' => 'advies',
                'label' => 'Graag advies',
                'icon' => '?',
                'lucide' => 'lightbulb',
            ],
            [
                'value' => 'weet_ik_niet',
                'label' => 'Weet ik niet',
                'icon' => '?',
                'lucide' => 'circle-help',
            ],
        ],
    ],

    [
        'step' => 3,
        'key' => 'urgentie',
        'label' => 'Hoe snel hulp nodig?',
        'help_text' => 'Kies hoe dringend uw aanvraag is.',
        'type' => 'options',
        'layout' => 'row',
        'required' => true,
        'options' => [
            [
                'value' => 'vandaag',
                'label' => 'Vandaag',
                'desc' => 'Met spoed — zo snel mogelijk',
                'icon' => '!',
                'lucide' => 'zap',
            ],
            [
                'value' => 'binnen_24_uur',
                'label' => 'Binnen 24 uur',
                'desc' => 'Dringend, maar niet acuut',
                'icon' => '24',
                'lucide' => 'clock',
            ],
            [
                'value' => 'deze_week',
                'label' => 'Deze week',
                'desc' => 'Op korte termijn',
                'icon' => '7',
                'lucide' => 'calendar',
            ],
            [
                'value' => 'binnen_2_weken',
                'label' => 'Binnen 2 weken',
                'desc' => 'Heeft even tijd',
                'icon' => '14',
                'lucide' => 'calendar-days',
            ],
            [
                'value' => 'geen_haast',
                'label' => 'Geen haast',
                'desc' => 'Ik oriënteer me vooral',
                'icon' => '⌛',
                'lucide' => 'hourglass',
            ],
        ],
    ],

    [
        'step' => 4,
        'key' => 'verwarming',
        'label' => 'Werkt de verwarming?',
        'help_text' => 'Dit helpt bij het beoordelen van de storing.',
        'type' => 'options',
        'layout' => 'tile',
        'required' => true,
        'options' => [
            [
                'value' => 'werkt_normaal',
                'label' => 'Werkt normaal',
                'icon' => '✓',
                'lucide' => 'check',
            ],
            [
                'value' => 'werkt_niet',
                'label' => 'Werkt niet',
                'icon' => '✕',
                'lucide' => 'x',
            ],
            [
                'value' => 'werkt_soms',
                'label' => 'Werkt soms',
                'icon' => '~',
                'lucide' => 'activity',
            ],
            [
                'value' => 'alleen_warm_water_probleem',
                'label' => 'Alleen warm water probleem',
                'icon' => '♨',
                'lucide' => 'flame',
            ],
            [
                'value' => 'weet_ik_niet',
                'label' => 'Weet ik niet',
                'icon' => '?',
                'lucide' => 'circle-help',
            ],
        ],
    ],

    [
        'step' => 5,
        'key' => 'warm_water',
        'label' => 'Heeft u warm water?',
        'help_text' => 'Geef aan of het warme water nog goed werkt.',
        'type' => 'options',
        'layout' => 'tile',
        'required' => true,
        'options' => [
            [
                'value' => 'ja',
                'label' => 'Ja',
                'icon' => '✓',
                'lucide' => 'check',
            ],
            [
                'value' => 'nee',
                'label' => 'Nee',
                'icon' => '✕',
                'lucide' => 'x',
            ],
            [
                'value' => 'soms',
                'label' => 'Soms',
                'icon' => '~',
                'lucide' => 'activity',
            ],
            [
                'value' => 'alleen_lauw',
                'label' => 'Alleen lauw',
                'icon' => '♨',
                'lucide' => 'thermometer',
            ],
            [
                'value' => 'weet_ik_niet',
                'label' => 'Weet ik niet',
                'icon' => '?',
                'lucide' => 'circle-help',
            ],
        ],
    ],

    [
        'step' => 6,
        'key' => 'leeftijd',
        'label' => 'Hoe oud is de ketel?',
        'help_text' => 'Een schatting is genoeg.',
        'type' => 'options',
        'layout' => 'tile',
        'required' => true,
        'options' => [
            [
                'value' => '0_5_jaar',
                'label' => '0-5 jaar',
                'icon' => '1',
                'num' => '‹5',
            ],
            [
                'value' => '5_10_jaar',
                'label' => '5-10 jaar',
                'icon' => '2',
                'num' => '5+',
            ],
            [
                'value' => '10_15_jaar',
                'label' => '10-15 jaar',
                'icon' => '3',
                'num' => '10+',
            ],
            [
                'value' => '15_plus_jaar',
                'label' => '15+ jaar',
                'icon' => '4',
                'num' => '15+',
            ],
            [
                'value' => 'weet_ik_niet',
                'label' => 'Weet ik niet',
                'icon' => '?',
                'lucide' => 'circle-help',
            ],
        ],
    ],

    [
        'step' => 7,
        'key' => 'fotos_toelichting',
        'label' => 'Foto’s en toelichting',
        'help_text' => 'Niet verplicht, maar helpt voor een betere offerte.',
        'type' => 'fields',
        'required' => false,
        'fields' => [
            [
                'key' => 'photos',
                'label' => 'Foto’s van de cv-ketel',
                'type' => 'file',
                'placeholder' => '',
                'autocomplete' => '',
                'required' => false,
                'full_width' => true,
                'multiple' => true,
                'accept' => 'image/jpeg,image/png,image/webp',
                'helper' => 'Foto’s van de ketel, leidingen, typeplaatje, rookgasafvoer of lekkage helpen bij een snellere beoordeling.',
            ],
            [
                'key' => 'message',
                'label' => 'Extra toelichting',
                'type' => 'textarea',
                'placeholder' => 'Bijv. foutcode, lekkage, lawaai of wanneer het probleem begon...',
                'autocomplete' => '',
                'required' => false,
                'full_width' => true,
                'helper' => 'Niet verplicht. Alles wat u invult helpt bij de beoordeling.',
            ],
        ],
    ],

    [
        'step' => 8,
        'key' => 'contact',
        'label' => 'Uw gegevens',
        'help_text' => 'Wij nemen contact op met advies of een offerte.',
        'type' => 'fields',
        'required' => true,
        'fields' => [
            [
                'key' => 'naam',
                'label' => 'Naam',
                'type' => 'text',
                'placeholder' => 'Voornaam Achternaam',
                'autocomplete' => 'name',
                'required' => true,
                'full_width' => true,
                'lucide' => 'user',
            ],
            [
                'key' => 'telefoon',
                'label' => 'Telefoon',
                'type' => 'tel',
                'placeholder' => '06 12345678',
                'autocomplete' => 'tel',
                'required' => true,
                'full_width' => true,
                'lucide' => 'phone',
            ],
            [
                'key' => 'email',
                'label' => 'E-mail',
                'type' => 'email',
                'placeholder' => 'naam@voorbeeld.nl',
                'autocomplete' => 'email',
                'required' => true,
                'full_width' => true,
                'lucide' => 'mail',
            ],
            [
                'key' => 'postcode',
                'label' => 'Postcode',
                'type' => 'text',
                'placeholder' => '1234 AB',
                'autocomplete' => 'postal-code',
                'required' => true,
            ],
            [
                'key' => 'plaats',
                'label' => 'Plaats',
                'type' => 'text',
                'placeholder' => 'Rotterdam',
                'autocomplete' => 'address-level2',
                'required' => true,
            ],
        ],
    ],
];
